### ISSUE TITLE
All/Final answers are not visible

### ISSUE THREAD

**Issue by phuesch** [yanniz0r/never-have-i-ever#1]
When the last participant of a game selects their answer, the game jumps directly to the next question so the final results of all participants, or at least the last answer, are/is not visible. 
It would be nice to have some time to discuss about the answers before the next question comes up.

**Comment by yanniz0r** [comment]
Fixed! Feel free to open again if the solution is insufficient

**Comment by phuesch** [comment]
Looks fine so far, just found one small issue - the chat shows the notification "[Player] has answered" also when you click on the next question button. Could be confusing.

**Comment by phuesch** [comment]
And another bug: 
If one player leaves the game before answering the question, it is not possible for other players to continue the game. 
Also it would be good to get a notification if a player leaves an active game.
