### ISSUE TITLE
Name geht unendlich Lang

### ISSUE THREAD

**Issue by LuckyBulgur** [yanniz0r/never-have-i-ever#13]
Es sollte einen Limit geben bei der Namen eingabe. Das Problem ist, das sonst der Ganze Bildschirm vom Chat überdeckt ist. Eine Blacklist mit Beleidigungen könnte man vllt. auch machen. Und beim Namen fehlt ein Minimum, weil man sonst auch einfach nur ein Leerzeichen als namen nehmen kann. Wenn man dann noch einen Frage beantwortet kommt eine Error Page

**Comment by yanniz0r** [comment]
Done!
