### ISSUE TITLE
Antwortzeit und Maxplayers Angabe

### ISSUE THREAD

**Issue by LuckyBulgur** [yanniz0r/never-have-i-ever#15]
Wenn man nichts eingibt, wäre es nicht schlecht wenn drunter stehen würde "Bitte gebe eine Zahl zwischen 10-60 bzw. 1-64 ein, sonst kannst du leider kein Spiel erstellen" oder allgemein ein Feedback mit einer Fehlermeldung, das man etwas eingeben soll:)

**Comment by yanniz0r** [comment]
Done!
