### ISSUE TITLE
Visuel Bug: Chat input field is displayed in front of chat

### ISSUE THREAD

**Issue by phuesch** [yanniz0r/never-have-i-ever#7]
As shown in the picture below, chat messages and notifications are laying behind the chat input field and, in addition, the chat is overflowing when getting too long, so the latest messages aren't shown.

![chat_bug](https://user-images.githubusercontent.com/49513706/107090535-a4da7100-6800-11eb-86ae-950c3044c81c.png)

**Comment by yanniz0r** [comment]
Done!
